stream_over_http_enabled: true
server:
  http_listen_port: 3200
  log_level: info

query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
    metadata_slo:
      duration_slo: 5s
      throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317" # Ensure this matches with OTLP receiver port on Tempo

ingester:
  max_block_duration: 5m
compactor:
  compaction:
    block_retention: 24h # Keep for a day for testing

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write # Prometheus remote write endpoint
        send_exemplars: true
  traces_storage:
    path: /var/tempo/generator/traces

storage:
  trace:
    backend: local # Using local backend for storage
    wal:
      path: /var/tempo/wal # WAL (Write-Ahead Log) storage path
    local:
      path: /var/tempo/blocks # Local block storage for traces

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks] # Enable the metrics generator
      generate_native_histograms: both # Generate histograms for spans and services
